---
- hosts: localhost
  tasks:
    - name: Install homebrew
      include_role:
        name: geerlingguy.mac.homebrew

    - name: Make sure homebrew bin is in path
      ansible.builtin.lineinfile:
        path: /etc/paths
        state: present
        line: '/opt/homebrew/bin'
      become: true
      become_user: root

    - name: 'add custom homebrew repos'
      tags:
        - addbrewrepos
      community.general.homebrew_tap:
        name: [
          adoptopenjdk/openjdk,
          fishtown-analytics/dbt,
          heroku/brew,
          homebrew/cask-versions,
          thoughtbot/formulae,
          weaveworks/tap,
        ]

    - name: Install core packages via brew casks
      community.general.homebrew_cask:
        name: "{{ item }}"
      ignore_errors: yes
      # Check https://formulae.brew.sh/cask/ for all installable casks
      with_items:
          - dropbox
          - firefox
          - google-chrome
          - slack
          - sublime-text
          - itsycal
          - karabiner-elements
          - vlc
          - github
          - sourcetree
          - intellij-idea
          - iterm2
          - zoom
          - betterzip
          - beyond-compare
          - microsoft-remote-desktop
          - visual-studio-code
          - visualvm
          - vmware-horizon-client
          - gimp
          - elmedia-player
          - meld
          - whatsapp
          - shottr
          - flycut

    - name: "Install homebrew packages"
      community.general.homebrew:
        name: [
          'curl',
          'wget',
          'mas',
          'openssl' ,
          'unzip',
          'zsh',
          'asdf',
          'iperf'
        ]
        state: present
        update_homebrew: yes

    - name: "Install from Mac app store"
      tags:
        - installappstoreapps
      shell: mas install {{ item }}
      with_items:
        - 497799835 # xcode

    - name: Get the path to ZSH
      become: false
      local_action: command which zsh
      register: zsh_path

    - name: "Ensure homebrew zsh is in allowed shells"
      lineinfile:
        path: /etc/shells
        line: "{{ zsh_path.stdout }}"
      become: true

    - name: Install Oh My ZSH
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      args:
        creates: "/Users/{{ lookup('env', 'USER') }}/.oh-my-zsh"

    - name: Set ZSH as the default shell
      shell: chsh -s $(which zsh) {{ lookup('env', 'USER') }}
      become: true

    - name: Download zshrc
      become: yes
      tags:
        - downloadconf
      uri:
        method: GET
        follow_redirects: true
        url: https://www.dropbox.com/s/5fobaj3p7g5uz9d/zshrc?dl=1
        dest: /tmp/.zshrc
      retries: 5

    - name: Download karabiner configuration
      become: yes
      tags:
        - downloadconf
      uri:
        method: GET
        follow_redirects: true
        url: https://www.dropbox.com/s/o60qxflm028n3k0/karabiner.json?dl=1
        dest: /tmp/karabiner.json
      retries: 5

    - name: Download sublime-text keymap
      become: yes
      tags:
        - downloadconf
      uri:
        method: GET
        follow_redirects: true
        url: https://www.dropbox.com/s/63tv3urrhfxbsih/sublime-keymap?dl=1
        dest: /tmp/sublime-keymap
      retries: 5

    - name: Download sublime-text insertdate.py
      become: yes
      tags:
        - downloadconf
      uri:
        method: GET
        follow_redirects: true
        url: https://www.dropbox.com/s/kvw6cr7ygyy8dp6/insertdate.py?dl=1
        dest: /tmp/insertdate.py
      retries: 5

    - name: Download .gitconfig 
      become: yes
      tags:
        - downloadconf
      uri:
        method: GET
        follow_redirects: true
        url: https://www.dropbox.com/s/ibb6g6b1rigq15e/gitconfig?dl=1
        dest: /tmp/gitconfig
      retries: 5

    - name: "Create a default ZSH configuration"
      become: yes
      tags:
        - applyconf
      template:
        src: /tmp/.zshrc
        dest: /Users/{{ lookup('env', 'USER') }}/.zshrc
        owner: "{{ lookup('env', 'USER') }}"
        force: yes

    - name: "Copy default karabiner-elements configuration"
      become: yes
      tags:
        - applyconf
      template:
        src: /tmp/karabiner.json
        dest: /Users/{{ lookup('env', 'USER') }}/.config/karabiner/karabiner.json
        owner: "{{ lookup('env', 'USER') }}"
        force: yes

    - name: "Copy default sublime-text keymap"
      become: yes
      tags:
        - applyconf
      template:
        src: /tmp/sublime-keymap
        dest: /Users/{{ lookup('env', 'USER') }}/Library/Application Support/Sublime Text 3/Packages/User/Default (OSX).sublime-keymap
        owner: "{{ lookup('env', 'USER') }}"
        force: yes

    - name: "Copy sublime-text script for insertdate"
      become: yes
      tags:
        - applyconf
      template:
        src: /tmp/insertdate.py
        dest: /Users/{{ lookup('env', 'USER') }}/Library/Application Support/Sublime Text 3/Packages/User/insertdate.py
        owner: "{{ lookup('env', 'USER') }}"
        force: yes

    - name: "Copy gitconfig"
      become: yes
      tags:
        - applyconf
      template:
        src: /tmp/gitconfig
        dest: /Users/{{ lookup('env', 'USER') }}/.gitconfig
        owner: "{{ lookup('env', 'USER') }}"
        force: yes

    - name: "Install asdf plugins"
      tags:
        - installasdfplugins
      shell: |
        asdf plugin-add {{ item }} || exit 0
      with_items:
        - nodejs
        - python
        - java

    - name: "Install Default Python"
      tags:
        - installdefaultpython
      shell: |
        asdf install python 3.10.0
        asdf global python 3.10.0
        pip3 install ansible
        asdf reshim python
